GET http://localhost:3001/ HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3001/users/?category=demolition HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3001/user/6091b5565e327a1bb0628cb4 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/users/6091b5565e327a1bb0628cb6 HTTP/1.1
Content-Type: application/json

{
  "tools": [{
    "name": "roto-zip",
    "category": "demolition",
    "owner": "Cullen Sharp",
    "borrowedBy": "",
    "Availbility": true
  }] 
}

###
DELETE http://localhost:3001/users/6091b5565e327a1bb0628cb4 HTTP/1.1
Content-Type: application/json

{
  "toolID":0,
}

###
PUT http://localhost:3001/borrow/6091b5565e327a1bb0628cb2 HTTP/1.1
Content-Type: application/json

{
  "borrowerID": "6091b5565e327a1bb0628cb4",
  "toolID":0,
  "Availbility": false
}

###
PUT http://localhost:3001/user/6091b5565e327a1bb0628cb0 HTTP/1.1
Content-Type: application/json

{
  "toolID": 0
  
}