GET http://localhost:3001/ HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3001/users/?category=demolition HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/users/6091b5565e327a1bb0628cb6 HTTP/1.1
Content-Type: application/json

{
  "tools": [{
    "name": "roto-zip",
    "category": "demolition",
    "owner": "Cullen Sharp",
    "borrowedBy": "",
    "Availbility": true
  }] 
}

###
DELETE http://localhost:3001/users/60909353d7efd8145adc4671 HTTP/1.1
Content-Type: application/json
